import 'dotenv/config'
import OpenAI from 'openai'
import { AgentInput, AgentResponse, AgentIntent, ChatMessage } from './types'
import { buildSystemPrompt, INTENT_DETECTION_PROMPT } from './prompts'

const DEEPSEEK_MODEL_ALIASES: Record<string, string> = {
  'deepseek-v4-pro': 'deepseek-v4-pro',
  'deepseek-v4-flash': 'deepseek-v4-flash',
  'hybrid-deepseek-gpt4o': 'deepseek-v4-flash',
  'hybrid-deepseek-pro-gpt4o': 'deepseek-v4-pro',
}

function resolveDeepSeekModel(model: string) {
  return DEEPSEEK_MODEL_ALIASES[model] ?? model
}

// Determina si el modelo es de DeepSeek
function isDeepSeek(model: string) {
  return model.startsWith('deepseek') || model.startsWith('hybrid-deepseek')
}

// Crea el cliente correcto según el modelo y las claves disponibles
function getClient(model: string, apiKey?: string, deepseekKey?: string): { client: OpenAI; resolvedModel: string } {
  if (isDeepSeek(model) && deepseekKey) {
    return {
      client: new OpenAI({ apiKey: deepseekKey, baseURL: 'https://api.deepseek.com/v1' }),
      resolvedModel: resolveDeepSeekModel(model),
    }
  }
  // Fallback: OpenAI
  const key = apiKey || process.env.OPENAI_API_KEY || ''
  return {
    client: new OpenAI({ apiKey: key }),
    resolvedModel: isDeepSeek(model) ? 'gpt-4o-mini' : model, // si no hay deepseek key, usa mini
  }
}

function deepSeekChatOptions(model: string) {
  return isDeepSeek(model)
    ? ({ extra_body: { thinking: { type: 'disabled' } } } as Record<string, unknown>)
    : {}
}

async function detectIntent(
  message: string,
  model: string,
  openaiKey?: string,
  deepseekKey?: string,
): Promise<{ intent: AgentIntent; confidence: number }> {
  const prompt = INTENT_DETECTION_PROMPT.replace('{message}', message)
  const { client, resolvedModel } = getClient(model, openaiKey, deepseekKey)

  try {
    const res = await client.chat.completions.create({
      model: isDeepSeek(model) ? resolvedModel : 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0,
      max_tokens: 60,
      ...deepSeekChatOptions(model),
    })
    const raw = res.choices[0].message.content ?? '{}'
    const parsed = JSON.parse(raw)
    return { intent: parsed.intent ?? 'general', confidence: parsed.confidence ?? 0.5 }
  } catch {
    return { intent: 'general', confidence: 0.5 }
  }
}

async function runOpenAIFallback(messages: ChatMessage[], apiKey?: string): Promise<string | null> {
  const key = apiKey || process.env.OPENAI_API_KEY || ''
  if (!key) return null

  try {
    const client = new OpenAI({ apiKey: key })
    const completion = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      messages,
      temperature: 0.7,
      max_tokens: 400,
    })
    const reply = completion.choices[0].message.content?.trim() || null
    if (reply) console.log('[agent] Reply generated by gpt-4o-mini fallback')
    return reply
  } catch (err: any) {
    console.error('[agent] OpenAI fallback error:', err?.status ?? err?.code ?? '', err?.message ?? err)
    return null
  }
}

export async function runAgent(input: AgentInput): Promise<AgentResponse> {
  const {
    incomingMessage, history, tenantPrompt, productName, productPrice,
    model: requestedModel, apiKey, deepseekKey, onLowCredits,
  } = input as AgentInput & { model?: string; apiKey?: string; deepseekKey?: string; onLowCredits?: () => void }

  const model = requestedModel ?? 'gpt-4o'

  const { intent, confidence } = await detectIntent(incomingMessage, model, apiKey, deepseekKey)

  if (intent === 'voucher') {
    return { reply: '¡Recibido! Estoy verificando tu comprobante de pago. En un momento te confirmo. 🙏', intent, confidence }
  }

  const systemPrompt = buildSystemPrompt({
    tenantId: '', systemPrompt: tenantPrompt,
    productName: productName ?? 'Producto', productPrice: productPrice ?? 0, handoffThreshold: 0.4,
  })

  const messages: ChatMessage[] = [
    { role: 'system', content: systemPrompt },
    ...history.slice(-30),
    { role: 'user', content: incomingMessage },
  ]

  const { client, resolvedModel } = getClient(model, apiKey, deepseekKey)

  try {
    const completion = await client.chat.completions.create({
      model: resolvedModel,
      messages,
      temperature: 0.7,
      frequency_penalty: 0.6,
      presence_penalty: 0.3,
      max_tokens: 400,
      ...deepSeekChatOptions(model),
    })

    const reply = completion.choices[0].message.content?.trim()
    if (!reply) {
      console.error(`[agent] Empty reply from ${resolvedModel}`)
      console.log(`[agent] Empty reply from ${resolvedModel}, trying gpt-4o-mini fallback`)
      const fallbackReply = isDeepSeek(model) ? await runOpenAIFallback(messages, apiKey) : null
      if (fallbackReply) return { reply: fallbackReply, intent, confidence }
      return { reply: '¡Hola! Estoy aquí para ayudarte. ¿En qué te puedo asistir? 😊', intent, confidence }
    }
    console.log(`[agent] Reply generated by ${resolvedModel}`)
    return { reply, intent, confidence }
  } catch (err: any) {
    const code = err?.status ?? err?.code ?? ''
    console.error(`[agent] API error (${resolvedModel}):`, code, err?.message ?? err)

    if (code === 402 || String(err?.message).includes('Insufficient Balance') || String(err?.message).includes('insufficient_quota')) {
      onLowCredits?.()
      return { reply: 'En este momento estoy con problemas técnicos. Por favor escríbeme en unos minutos. 🙏', intent, confidence }
    }
    return { reply: '¡Hola! ¿En qué te puedo ayudar hoy? 😊', intent, confidence }
  }
}
